version: "3.9"
services:
  analysis:
    image: analysis:latest
    build: .
    stdin_open: true
    tty: true
    volumes:
      - ./CSKG:/CSKG
      - ./ConceptNet:/ConceptNet
      - ./conv.tsv:/conv.tsv
      - ./eml.py:/eml.py
    command: /bin/bash
